# ==================================
# stylish-haskell configuration file
# ==================================

steps:
  - module_header:
      indent: 4
      sort: false
      separate_lists: false
      break_where: single
      open_bracket: next_line

  - records:
      equals: "indent 2"
      first_field: same_line
      field_comment: 2
      deriving: 2
      via: "indent 2"
      sort_deriving: true
      break_enums: true
      break_single_constructors: true
      curried_context: false

  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always

  - imports:
      align: file
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: false
      space_surround: true
      post_qualify: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - tabs:
      spaces: 2

  - trailing_whitespace: {}

columns: 120
newline: lf
cabal: true
